import { TCharacteristic } from './types';

export const mockContactsData = {
  type: 'contacts',
  id: 0,
  address: 'г. Краснодар, ул. Римково 64',
  opening_hours: 'Пн-пт / 10:00 - 17:30',
  phone: '+7 (499) 342-33-24',
  email: 'alba.frolov@gmail.com',
  telegram: '#',
  instagram: '#',
  vk: '#',
  map: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2819.8111710142707!2d38.958102615451274!3d45.0287585704135!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x40f04fa5fdab425f%3A0xd09e60dccfdc40f4!2z0YPQuy4g0KfQutCw0LvQvtCy0LAsIDEsINCa0YDQsNGB0L3QvtC00LDRgCwg0JrRgNCw0YHQvdC-0LTQsNGA0YHQutC40Lkg0LrRgNCw0LksIDM1MDAwMA!5e0!3m2!1sru!2sru!4v1678171046142!5m2!1sru!2sru',
};

export const mockCharacteristicsData: TCharacteristic[] = [
  {
    type: 'characteristics',
    id: 'rrewecdsc',
    name: 'Чехол Luxo original green',
    product_id: 'string44',
    stock: 20,
    in_cart: 0,
    price: '510.00',
    discount: 0,
    discounted_price: '510.00',
    color: 'Black',
    is_new: true,

    is_hit: true,
    in_favorite: false,
    photo: {
      front:
        'https://itechstore.ru/media/images/products/2022/7/0fe4203947ee11ebb2be3cecef20832b_e37732805ad111ebb2be3cecef20832b.jpg',
      left: 'https://iphoriya.ru/wp-content/uploads/apple-silicone-case-iphone-11-vitamin-c.jpeg',
      inside: 'https://img.mvideo.ru/Pdb/50129627b.jpg',
    },
  },
  {
    type: 'characteristics',
    id: 'rrewecdscs',
    name: 'Чехол Luxo original gray',
    product_id: 'string44',
    stock: 0,
    in_cart: 0,
    price: '487.00',
    discount: 20,
    discounted_price: '310.00',
    color: 'Black',
    is_new: true,

    is_hit: true,
    in_favorite: false,
    photo: {
      front:
        'https://itechstore.ru/media/images/products/2022/7/0fe4203947ee11ebb2be3cecef20832b_e37732805ad111ebb2be3cecef20832b.jpg',
      left: 'https://iphoriya.ru/wp-content/uploads/apple-silicone-case-iphone-11-vitamin-c.jpeg',
      inside: 'https://img.mvideo.ru/Pdb/50129627b.jpg',
    },
  },
  {
    type: 'characteristics',
    id: 'rrewecdscd',
    name: 'Чехол Luxo original yellow',
    product_id: 'string44',
    stock: 200,
    in_cart: 0,
    price: '460.00',
    discount: 13,
    discounted_price: '310.00',
    color: 'Black',
    is_new: true,

    is_hit: true,
    in_favorite: false,
    photo: {
      front:
        'https://itechstore.ru/media/images/products/2022/7/0fe4203947ee11ebb2be3cecef20832b_e37732805ad111ebb2be3cecef20832b.jpg',
      left: 'https://iphoriya.ru/wp-content/uploads/apple-silicone-case-iphone-11-vitamin-c.jpeg',
      inside: 'https://img.mvideo.ru/Pdb/50129627b.jpg',
    },
  },
  {
    type: 'characteristics',
    id: 'rrewecdscf',
    name: 'Чехол Luxo original black',
    product_id: 'string44',
    stock: 200,
    in_cart: 0,
    price: '410.00',
    discount: 21,
    discounted_price: '290.00',
    color: 'Black',
    is_new: false,

    is_hit: true,
    in_favorite: false,
    photo: {
      front:
        'https://itechstore.ru/media/images/products/2022/7/0fe4203947ee11ebb2be3cecef20832b_e37732805ad111ebb2be3cecef20832b.jpg',
      left: 'https://iphoriya.ru/wp-content/uploads/apple-silicone-case-iphone-11-vitamin-c.jpeg',
      inside: 'https://img.mvideo.ru/Pdb/50129627b.jpg',
    },
  },
  {
    type: 'characteristics',
    id: 'rrewecdscdt',
    name: 'Чехол Luxo original yellow',
    product_id: 'string44',
    stock: 200,
    in_cart: 0,
    price: '460.00',
    discount: 15,
    discounted_price: '340.00',
    color: 'Black',
    is_new: true,

    is_hit: true,
    in_favorite: false,
    photo: {
      front:
        'https://itechstore.ru/media/images/products/2022/7/0fe4203947ee11ebb2be3cecef20832b_e37732805ad111ebb2be3cecef20832b.jpg',
      left: 'https://iphoriya.ru/wp-content/uploads/apple-silicone-case-iphone-11-vitamin-c.jpeg',
      inside: 'https://img.mvideo.ru/Pdb/50129627b.jpg',
    },
  },
  {
    type: 'characteristics',
    id: 'rrewecdscfr',
    name: 'Чехол Luxo original black',
    product_id: 'string44',
    stock: 200,
    in_cart: 0,
    price: '410.00',
    discount: 30,
    discounted_price: '280.00',
    color: 'Black',
    is_new: true,

    is_hit: true,
    in_favorite: false,
    photo: {
      front:
        'https://itechstore.ru/media/images/products/2022/7/0fe4203947ee11ebb2be3cecef20832b_e37732805ad111ebb2be3cecef20832b.jpg',
      left: 'https://iphoriya.ru/wp-content/uploads/apple-silicone-case-iphone-11-vitamin-c.jpeg',
      inside: 'https://img.mvideo.ru/Pdb/50129627b.jpg',
    },
  },
];

export const mockCategories = [
  {
    type: 'categories',
    id: 1,
    name: 'Защитные чехлы',
    icon: '../../images/icons/case.svg',
    photo: 'photo/glass_photo.jpg',
    level: 0,
    slug: 'stekla-dlya-iphone',
    parend_id: null,
    position: 1,
    mob_position: 1,
  },
  {
    type: 'categories',
    id: 2,
    name: 'Защитные стёкла',
    icon: '../../images/icons/case.svg',
    photo: 'photo/glass_photo.jpg',
    level: 0,
    slug: 'stekla-dlya-iphone',
    parend_id: null,
    position: 2,
    mob_position: 2,
  },
  {
    type: 'categories',
    id: 3,
    name: 'Ремешки',
    icon: '../../images/icons/case.svg',
    photo: 'photo/glass_photo.jpg',
    level: 0,
    slug: 'stekla-dlya-iphone',
    parend_id: null,
    position: 6,
    mob_position: 3,
  },
  {
    type: 'categories',
    id: 4,
    name: 'Зарядные устройства',
    icon: '../../images/icons/case.svg',
    photo: 'photo/glass_photo.jpg',
    level: 0,
    slug: 'stekla-dlya-iphone',
    parend_id: null,
    position: 4,
    mob_position: 5,
  },
  {
    type: 'categories',
    id: 7,
    name: 'Кабели',
    icon: '../../images/icons/case.svg',
    photo: 'photo/glass_photo.jpg',
    level: 0,
    slug: 'stekla-dlya-iphone',
    parend_id: null,
    position: 3,
    mob_position: 4,
  },
  {
    type: 'categories',
    id: 8,
    name: 'Колонки и наушники',
    icon: '../../images/icons/case.svg',
    photo: 'photo/glass_photo.jpg',
    level: 0,
    slug: 'stekla-dlya-iphone',
    parend_id: null,
    position: 8,
    mob_position: 8,
  },
  {
    type: 'categories',
    id: 9,
    name: 'Детские товары',
    icon: '../../../images/icons/cable.svg',
    photo: 'photo/glass_photo.jpg',
    level: 0,
    slug: 'stekla-dlya-iphone',
    parend_id: null,
    position: 9,
    mob_position: 9,
  },
  {
    type: 'categories',
    id: 5,
    name: 'Гаджеты',
    icon: '../../images/icons/case.svg',
    photo: 'photo/glass_photo.jpg',
    level: 0,
    slug: 'stekla-dlya-iphone',
    parend_id: null,
    position: 7,
    mob_position: 7,
  },
  {
    type: 'categories',
    id: 6,
    name: 'Автотовары',
    icon: '../../images/icons/case.svg',
    photo: 'photo/glass_photo.jpg',
    level: 0,
    slug: 'stekla-dlya-iphone',
    parend_id: null,
    position: 5,
    mob_position: 6,
  },
];

export const mockBrands = [
  {
    type: 'brands',
    id: 1,
    name: 'Xiaomi',
    logo: 'photo/xiaomi.jpg',
    in_brand_section: true,
  },
  {
    type: 'brands',
    id: 2,
    name: 'Xiaomi',
    logo: 'photo/xiaomi.jpg',
    in_brand_section: true,
  },
  {
    type: 'brands',
    id: 3,
    name: 'Xiaomi',
    logo: 'photo/xiaomi.jpg',
    in_brand_section: true,
  },
  {
    type: 'brands',
    id: 4,
    name: 'Xiaomi',
    logo: 'photo/xiaomi.jpg',
    in_brand_section: true,
  },
  {
    type: 'brands',
    id: 5,
    name: 'Xiaomi',
    logo: 'photo/xiaomi.jpg',
    in_brand_section: true,
  },
];
